Trying parallel archive for CerealOutputArchive
Does not compile

```
In file included from /Users/keceli/tmp/nwx/madness/src/madness/world/worlddc.h:46,
                 from /Users/keceli/tmp/nwx/madness/src/madness/world/MADworld.h:47,
                 from /Users/keceli/tmp/nwx/madness/src/madness/world/redirectio.cc:33:
/Users/keceli/tmp/nwx/madness/src/madness/world/parallel_archive.h: In instantiation of 'madness::archive::BaseParallelArchive<Archive>::BaseParallelArchive() [with Archive = madness::archive::CerealOutputArchive<cereal::BinaryOutputArchive>]':
/Users/keceli/tmp/nwx/madness/src/madness/world/parallel_archive.h:310:43:   required from here
/Users/keceli/tmp/nwx/madness/src/madness/world/parallel_archive.h:83:62: error: no matching function for call to 'madness::archive::CerealOutputArchive<cereal::BinaryOutputArchive>::CerealOutputArchive()'
   83 |                 : world(nullptr), ar(), nio(0), do_fence(true) {}
      |                                                              ^
```